// ---------------------------------------------------------------------------
// Assembling the six Midnight providers and the CrediFi CompiledContract
// binding against real Preprod endpoints and the local proof server.
//
// NOTE ON TYPES: the CrediFi contract is generated by compact-runtime 0.16.0
// (a class-based adapter that also carries `impureCircuits`), while
// `midnight-js-contracts` 4.1.1 binds contracts through compact-js 2.5.1's
// effect-style `CompiledContract`. The official 4.x docs explicitly surface
// this pairing hazard ("expected instance of ..."). The binding works at
// runtime; the casts below reconcile the two type systems.
// ---------------------------------------------------------------------------
import { createHash } from "node:crypto";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import { type MidnightProviders } from "@midnight-ntwrk/midnight-js-types";
import { Contract } from "./managed/credifi/contract/index.js";
import { CrediFiPrivateState, witnesses } from "./witnesses.js";
import { CrediFiWalletProvider } from "./credifi-wallet-provider.js";
import {
  INDEXER_URL,
  INDEXER_WS_URL,
  PROOF_SERVER_URL,
  CREDIFI_MANAGED_PATH,
} from "./config.js";
import { type WalletContext } from "./wallet.js";

/**
 * Domain-separated admin secret recovered only from the deployer seed. The
 * CrediFi constructor derives `contractAdmin` from `getUserSecret()`, so the
 * deployer of this contract is its admin. Never printed.
 */
export function deriveAdminSecret(seed: Uint8Array): Uint8Array {
  const domain = Buffer.from("credifi:admin:deploy:v1", "utf8");
  return createHash("sha256").update(domain).update(seed).digest();
}

/** Initial private state used to deploy CrediFi. Only the admin secret matters
 * for the constructor; the credential fields are placeholders. */
export function deployPrivateState(adminSecret: Uint8Array): CrediFiPrivateState {
  return {
    monthlyIncome: 0n,
    previousDefaultFlag: 0n,
    credentialSignature: { announcement: { x: 0n, y: 0n }, response: 0n },
    credentialIssuerId: 1n,
    userSecretKey: adminSecret,
  };
}

const CIRCUITS = ["requestVerification", "registerIssuer", "removeIssuer"] as const;

export type CrediFiProviders = MidnightProviders<
  (typeof CIRCUITS)[number],
  "credifiPrivateState",
  CrediFiPrivateState
>;

/** Builds the CompiledContract binding for CrediFi against its compile assets. */
export function buildCompiledContract(): CompiledContract.CompiledContract<any, CrediFiPrivateState, never> {
  // The generated compact-runtime 0.16.0 Contract class (which also exposes
  // `impureCircuits`) and compact-js 2.5.1's effect-style CompiledContract have
  // type-level mismatch (a documented 4.x pairing hazard). We build through the
  // REAL combinators so the runtime object is correct, and keep the signature
  // typed for the caller.
  const cc = CompiledContract as any;
  const withWitnesses = cc.withWitnesses(cc.make("credifi", Contract), witnesses);
  const bound = cc.withCompiledFileAssets(withWitnesses, CREDIFI_MANAGED_PATH);
  return bound as CompiledContract.CompiledContract<any, CrediFiPrivateState, never>;
}

export function buildProviders(
  ctx: WalletContext,
  privateStatePassword: string,
): {
  providers: CrediFiProviders;
  compiledContract: CompiledContract.CompiledContract<any, CrediFiPrivateState, never>;
} {
  const accountId = String(ctx.unshieldedKeystore.getBech32Address());

  const privateStateProvider = levelPrivateStateProvider({
    privateStateStoreName: "credifi-private-state",
    signingKeyStoreName: "credifi-signing-keys",
    privateStoragePasswordProvider: () => privateStatePassword,
    accountId,
  });

  const publicDataProvider = indexerPublicDataProvider(INDEXER_URL, INDEXER_WS_URL);

  const zkConfigProvider = new NodeZkConfigProvider<never>(CREDIFI_MANAGED_PATH);

  const proofProvider = httpClientProofProvider(PROOF_SERVER_URL, zkConfigProvider);

  const walletAndMidnightProvider = new CrediFiWalletProvider(
    ctx.wallet,
    ctx.shieldedSecretKeys,
    ctx.dustSecretKey,
  );

  const providers: CrediFiProviders = {
    privateStateProvider,
    publicDataProvider,
    zkConfigProvider,
    proofProvider,
    walletProvider: walletAndMidnightProvider,
    midnightProvider: walletAndMidnightProvider,
  };

  return { providers, compiledContract: buildCompiledContract() };
}
